CREATE TABLE IF NOT EXISTS course (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(80) NOT NULL UNIQUE,
  title varchar(160) NOT NULL,
  teaser varchar(500) NOT NULL,
  duration varchar(80) NOT NULL,
  price numeric(8,2) NOT NULL
);
ALTER TABLE course ADD COLUMN IF NOT EXISTS booking_url varchar(2000) NOT NULL DEFAULT '';

-- Preserve the previous booking schema for importing historical PayPal bookings.
-- New bookings and payments are handled by Purple Slot, not this table.
CREATE TABLE IF NOT EXISTS booking (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES course(id),
  customer_name varchar(120) NOT NULL,
  customer_email varchar(180) NOT NULL,
  paypal_order_id varchar(100) NOT NULL UNIQUE,
  status varchar(20) NOT NULL,
  created_at timestamp(0) without time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_booking_course ON booking(course_id);
CREATE TABLE IF NOT EXISTS site_setting (
  setting_key varchar(80) PRIMARY KEY,
  setting_value text NOT NULL
);
CREATE TABLE IF NOT EXISTS site_image (
  id uuid PRIMARY KEY,
  media_type text NOT NULL CHECK (media_type IN ('image/png', 'image/jpeg', 'image/webp')),
  data_base64 text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS admin_session (
  token_hash varchar(64) PRIMARY KEY,
  expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_admin_session_expiry ON admin_session(expires_at);
CREATE TABLE IF NOT EXISTS request_limit (
  key varchar(64) PRIMARY KEY,
  attempts integer NOT NULL,
  expires_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_request_limit_expiry ON request_limit(expires_at);
