// One registry for public copy, editor labels, defaults and server validation.
export const contentGroups = [
  { name: 'Allgemein & Fußzeile', fields: [
    ['siteName', 'Name der Website', 'Yoga mit Anna'],
    ['siteDescription', 'Beschreibung der Website', 'Achtsame Bewegung und ehrliche Verbindung für mehr Ruhe, Stärke und Wohlbefinden.', 'textarea'],
    ['footerText', 'Fußzeile ({year} = aktuelles Jahr)', '© {year} Yoga mit Anna'],
    ['bookingUrl', 'Purple-Slot-Studiolink', 'https://find-your-flow.purpleslot.io/', 'booking'],
    ['menuToggleLabel', 'Menü-Schaltfläche: zugängliche Beschriftung', 'Menü öffnen oder schließen'],
  ] },
  { name: 'Startseite', fields: [
    ['heroEyebrow', 'Text über der Überschrift', 'YOGA FÜR JEDE LEBENSPHASE'],
    ['heroTitle', 'Überschrift', 'Ankommen. Atmen. Bei dir sein.'],
    ['heroText', 'Einleitung', 'Achtsame Bewegung und ehrliche Verbindung für mehr Ruhe, Stärke und Wohlbefinden.', 'textarea'],
    ['heroButtonLabel', 'Schaltfläche', 'Deine erste Stunde'],
    ['heroButtonHref', 'Ziel der Schaltfläche', '/angebote/?slug=offene-stunden', 'link'],
    ['heroImage', 'Bildadresse (leer = Standardbild)', '', 'image'],
    ['heroImageAlt', 'Bildbeschreibung', 'Anna beim Yoga'],
    ['homeCoursesTitle', 'Überschrift der Angebote', 'Annas Angebote'],
    ['courseButtonLabel', 'Schaltfläche an den Angeboten', 'Mehr erfahren'],
    ['coursesEmptyText', 'Text ohne Angebote', 'Neue Angebote findest du hier in Kürze.'],
  ] },
  { name: 'Über mich', fields: [
    ['aboutEyebrow', 'Text über der Überschrift', 'ÜBER MICH'],
    ['aboutTitle', 'Überschrift', 'Hallo, ich bin Anna.'],
    ['aboutText', 'Text', 'Auf dieser Website findest du die Angebote und Informationen zur Buchung. Bei Fragen kannst du über das Kontaktformular Kontakt aufnehmen.', 'textarea'],
    ['aboutImage', 'Bildadresse (leer = Startseitenbild)', '', 'image'],
    ['aboutImageAlt', 'Bildbeschreibung', 'Anna'],
  ] },
  { name: 'Angebote & Buchung', fields: [
    ['offerIntro', 'Allgemeiner Angebotstext', 'Sanfte Übungen, bewusste Atmung und alltagstaugliche Impulse – ohne erforderliche Vorerfahrung.', 'textarea'],
    ['bookingTitle', 'Überschrift der Buchung', 'Buchung'],
    ['bookingText', 'Buchungshinweis', 'Verfügbare Termine und die verbindliche Buchung findest du bei Purple Slot.', 'textarea'],
    ['bookingButtonLabel', 'Buchungsschaltfläche', 'Bei Purple Slot buchen'],
    ['bookingUnavailableText', 'Text ohne Buchungslink', 'Für dieses Angebot ist die Online-Buchung noch nicht verfügbar.', 'textarea'],
    ['bookingContactLabel', 'Kontakt-Schaltfläche', 'Anna kontaktieren'],
    ['bookingContactHref', 'Kontakt-Ziel', '/kontakt/', 'link'],
    ['offerSelectText', 'Text ohne ausgewählten Kurs', 'Bitte wähle ein Angebot auf der Startseite.'],
    ['offersBackLabel', 'Zurück-Schaltfläche', 'Zu den Angeboten'],
    ['offerLoadingText', 'Ladeanzeige', 'Angebot wird geladen …'],
    ['offerMissingText', 'Nicht verfügbares Angebot', 'Dieses Angebot ist nicht verfügbar.'],
  ] },
  { name: 'Kontaktformular', fields: [
    ['contactTitle', 'Überschrift', 'Schreib Anna'],
    ['contactIntro', 'Einleitung', 'Anna freut sich auf deine Nachricht.', 'textarea'],
    ['contactNameLabel', 'Feld: Name', 'Name'],
    ['contactEmailLabel', 'Feld: E-Mail', 'E-Mail'],
    ['contactSubjectLabel', 'Feld: Betreff', 'Betreff'],
    ['contactMessageLabel', 'Feld: Nachricht', 'Nachricht'],
    ['contactButtonLabel', 'Absenden-Schaltfläche', 'Nachricht senden'],
    ['contactSendingLabel', 'Schaltfläche während des Versands', 'Wird gesendet …'],
    ['contactSuccessText', 'Erfolgsnachricht', 'Deine Nachricht wurde versendet.'],
    ['contactErrorText', 'Fehlermeldung', 'Die Nachricht konnte nicht versendet werden. Bitte versuche es später erneut.', 'textarea'],
    ['contactPrivacyText', 'Datenschutzhinweis', '', 'textarea'],
    ['contactPrivacyLabel', 'Beschriftung des Datenschutzlinks', 'Datenschutz'],
    ['contactPrivacyHref', 'Datenschutz-Link (optional)', '', 'link'],
  ] },
  { name: 'Fehler- und Hinweistexte', fields: [
    ['coursesErrorText', 'Angebote nicht ladbar', 'Die Angebote können gerade nicht geladen werden. Bitte versuche es später erneut oder kontaktiere Anna.', 'textarea'],
    ['notFoundTitle', 'Überschrift für fehlende Seiten', 'Seite nicht gefunden'],
    ['notFoundText', 'Text für fehlende Seiten', 'Die gewünschte Seite ist nicht verfügbar.'],
    ['homeLinkLabel', 'Link zur Startseite', 'Zur Startseite'],
    ['pageLoadingText', 'Seite wird geladen', 'Seite wird geladen …'],
    ['pageErrorText', 'Seite nicht ladbar', 'Diese Seite konnte nicht geladen werden. Bitte versuche es später erneut.'],
  ] },
];
export const textDefaults = Object.fromEntries(contentGroups.flatMap(group => group.fields.map(([key, , value]) => [key, value])));
export const defaults = {
  ...textDefaults,
  navigation: [
    { id: 'home', label: 'Home', type: 'link', href: '/', visible: true, newTab: false, children: [] },
    { id: 'about', label: 'Über mich', type: 'link', href: '/ueber-mich/', visible: true, newTab: false, children: [] },
    { id: 'courses', label: 'Angebote', type: 'courses', href: '', visible: true, newTab: false, children: [] },
    { id: 'contact', label: 'Kontakt', type: 'link', href: '/kontakt/', visible: true, newTab: false, children: [] },
    { id: 'booking', label: 'Buchen', type: 'booking', href: '', visible: true, newTab: true, children: [] },
  ],
  footerNavigation: [],
  pages: [
    { id: 'legal-imprint', slug: 'impressum', title: 'Impressum', eyebrow: '', intro: '', description: '', published: false, sections: [
      { id: 'imprint-provider', title: 'Anbieterangaben', body: '', image: '', imageAlt: '', buttonLabel: '', buttonHref: '' },
      { id: 'imprint-contact', title: 'Kontakt', body: '', image: '', imageAlt: '', buttonLabel: '', buttonHref: '' },
    ] },
    { id: 'legal-privacy', slug: 'datenschutz', title: 'Datenschutz', eyebrow: '', intro: '', description: '', published: false, sections: [
      { id: 'privacy-body', title: 'Datenschutzhinweise', body: '', image: '', imageAlt: '', buttonLabel: '', buttonHref: '' },
    ] },
  ],
};
